name: Build and Test
run-name: Testing out changes 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package
        run: yarn install
      - name: Install testing-app
        working-directory: ./testing-app
        run: yarn install
      - name: Run tests
        working-directory: ./testing-app
        run: yarn run test